import type { TarotCard } from "./types";

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: "the-fool",
    name: "愚者 The Fool",
    arcana: "major",
    number: 0,
    keywords: ["开始", "自由", "冒险", "直觉"],
    upright: "新的旅程正在开启。带着好奇与信任迈出第一步，但记得给自己留一点安全绳。",
    reversed: "冲动或逃避责任的迹象。先把信息补齐、再决定是否要跳。",
  },
  {
    id: "the-magician",
    name: "魔术师 The Magician",
    arcana: "major",
    number: 1,
    keywords: ["行动", "资源", "掌控", "表达"],
    upright: "你手上已经有足够资源。把想法说清楚、把计划拆小，马上就能动起来。",
    reversed: "能量分散或“说得多做得少”。聚焦一个目标，避免用话术掩盖不确定。",
  },
  {
    id: "the-high-priestess",
    name: "女祭司 The High Priestess",
    arcana: "major",
    number: 2,
    keywords: ["直觉", "隐秘", "等待", "洞察"],
    upright: "答案在你心里。先观察、少表态，保持边界感，你会看见更深的真相。",
    reversed: "忽视直觉或被情绪噪音淹没。把外界意见先关掉，回到自己的感觉。",
  },
  {
    id: "the-empress",
    name: "皇后 The Empress",
    arcana: "major",
    number: 3,
    keywords: ["滋养", "丰盛", "关系", "创造"],
    upright: "适合培养与生长：关系、作品或自我照顾都会开花结果。温柔但坚定。",
    reversed: "过度付出或失衡的照顾。先把自己补满，再谈给予。",
  },
  {
    id: "the-emperor",
    name: "皇帝 The Emperor",
    arcana: "major",
    number: 4,
    keywords: ["规则", "结构", "领导", "责任"],
    upright: "建立秩序与规则会帮你稳住局面。用清晰的边界换来长期安全感。",
    reversed: "控制欲或结构僵化。放松一点“必须”，允许协作与弹性。",
  },
  {
    id: "the-hierophant",
    name: "教皇 The Hierophant",
    arcana: "major",
    number: 5,
    keywords: ["传统", "学习", "导师", "制度"],
    upright: "遵循成熟路径会更顺：找老师、参考经验、用制度化方法推进。",
    reversed: "你想走不一样的路。打破陈规没问题，但要知道自己在挑战什么。",
  },
  {
    id: "the-lovers",
    name: "恋人 The Lovers",
    arcana: "major",
    number: 6,
    keywords: ["选择", "价值观", "关系", "对齐"],
    upright: "关键在“选择”。对齐价值观，做一个你愿意为之负责的决定。",
    reversed: "犹豫、暧昧或价值观不一致。先弄清底线，否则关系或合作难稳定。",
  },
  {
    id: "the-chariot",
    name: "战车 The Chariot",
    arcana: "major",
    number: 7,
    keywords: ["推进", "胜利", "意志", "掌舵"],
    upright: "你能赢，但靠的是自律与方向感。把分心的事收回，把节奏拉稳。",
    reversed: "用力过猛或失控。先重新校准目标，再上路。",
  },
  {
    id: "strength",
    name: "力量 Strength",
    arcana: "major",
    number: 8,
    keywords: ["温柔的力量", "耐心", "勇气", "自我驯服"],
    upright: "真正的强大来自稳定与耐心。用温柔的方式坚持，你会获得长期胜利。",
    reversed: "自我怀疑或情绪失控。先照顾情绪，再谈行动。",
  },
  {
    id: "the-hermit",
    name: "隐者 The Hermit",
    arcana: "major",
    number: 9,
    keywords: ["独处", "反思", "寻找", "智慧"],
    upright: "暂时放慢是对的。独处、复盘、做减法，会让你找到更清晰的方向。",
    reversed: "过度封闭或逃避现实。你需要一点支持与连接，不必一个人扛。",
  },
  {
    id: "wheel-of-fortune",
    name: "命运之轮 Wheel of Fortune",
    arcana: "major",
    number: 10,
    keywords: ["转机", "周期", "机会", "变化"],
    upright: "局势在转动，机会窗口出现。顺势而为，同时做好应变预案。",
    reversed: "重复旧模式或抗拒变化。先承认“周期在变”，再决定怎么调整。",
  },
  {
    id: "justice",
    name: "正义 Justice",
    arcana: "major",
    number: 11,
    keywords: ["公平", "因果", "契约", "清算"],
    upright: "回到事实与规则。用证据说话、把协议写清楚，结果会更公正。",
    reversed: "偏见或信息不对称。先把真相补齐，再做判断。",
  },
  {
    id: "the-hanged-man",
    name: "倒吊人 The Hanged Man",
    arcana: "major",
    number: 12,
    keywords: ["暂停", "换视角", "牺牲", "顿悟"],
    upright: "现在不适合硬推。换个角度、先让局面停一下，你会得到关键领悟。",
    reversed: "卡住不动或无谓牺牲。要么改变方法，要么及时止损。",
  },
  {
    id: "death",
    name: "死神 Death",
    arcana: "major",
    number: 13,
    keywords: ["结束", "转化", "告别", "重生"],
    upright: "该结束的就结束。清理旧模式/旧关系，为新的阶段腾位置。",
    reversed: "抗拒结束会拖累你。允许告别，转化才会发生。",
  },
  {
    id: "temperance",
    name: "节制 Temperance",
    arcana: "major",
    number: 14,
    keywords: ["平衡", "调和", "节奏", "疗愈"],
    upright: "把两端调到中间：节奏、作息、关系都需要更“刚刚好”。慢慢来更快。",
    reversed: "失衡或过度。你需要重新设定边界和节奏。",
  },
  {
    id: "the-devil",
    name: "恶魔 The Devil",
    arcana: "major",
    number: 15,
    keywords: ["欲望", "执念", "束缚", "诱惑"],
    upright: "你被某种执念/诱惑拉着走。看清代价，才能决定要不要继续。",
    reversed: "你正在松绑。把“我必须”改成“我选择”，自由度会上来。",
  },
  {
    id: "the-tower",
    name: "高塔 The Tower",
    arcana: "major",
    number: 16,
    keywords: ["突变", "真相", "崩塌", "重建"],
    upright: "旧结构在被打碎，真相会突然显现。别恋战废墟，及时重建才是关键。",
    reversed: "你在避免一场必要的改变。越拖越痛，先拆掉不稳的部分。",
  },
  {
    id: "the-star",
    name: "星星 The Star",
    arcana: "major",
    number: 17,
    keywords: ["希望", "疗愈", "愿景", "信任"],
    upright: "希望回来了。把愿景写下来，做一件小事兑现它，你会越走越亮。",
    reversed: "信心不足或失望。先补充能量：休息、求助、把目标调小一点。",
  },
  {
    id: "the-moon",
    name: "月亮 The Moon",
    arcana: "major",
    number: 18,
    keywords: ["迷雾", "情绪", "潜意识", "不确定"],
    upright: "信息不完全，情绪容易放大。别急着定论，先验证事实。",
    reversed: "迷雾在散。你会逐渐看清真相，但仍要避免自我欺骗。",
  },
  {
    id: "the-sun",
    name: "太阳 The Sun",
    arcana: "major",
    number: 19,
    keywords: ["成功", "清晰", "喜悦", "坦诚"],
    upright: "结果偏正向：清晰、被看见、被支持。把你的真实与热情拿出来。",
    reversed: "快乐被阴影遮住。注意疲惫与自我否定，先恢复精力再冲刺。",
  },
  {
    id: "judgement",
    name: "审判 Judgement",
    arcana: "major",
    number: 20,
    keywords: ["觉醒", "复盘", "召唤", "决定"],
    upright: "是时候做最终决定并承担它。复盘过去，你会知道自己真正要什么。",
    reversed: "拖延或害怕被评判。你需要先原谅自己，才能前进。",
  },
  {
    id: "the-world",
    name: "世界 The World",
    arcana: "major",
    number: 21,
    keywords: ["完成", "整合", "阶段性胜利", "新循环"],
    upright: "一个阶段圆满收束。庆祝成果，同时准备开启下一轮成长。",
    reversed: "差临门一脚。补齐最后的拼图（资源/沟通/收尾），就能完成。",
  },
];

