import type { TarotCard } from "./types";
import { createMinorArcana } from "./knowledge";

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: "the-fool",
    name: "愚者",
    arcana: "major",
    number: 0,
    keywords: ["开始", "信任", "自由", "冒险"],
    upright: "你站在一个新入口前。愚者不是鲁莽，而是提醒你：有些路只有开始走，才会看见下一步。",
    reversed: "你可能把冲动误认为自由，或因为害怕犯错而迟迟不动。先确认风险，再允许自己迈出小步。",
    archetype: "初学者与旅人",
    light: "开放、轻盈、愿意尝试。",
    shadow: "逃避责任、过度天真或无计划冒险。",
    reflectionQuestions: ["我真正想开始的是什么？", "我能把风险缩小到哪一步？"],
    actionAdvice: ["做一个低风险试验。", "写下最坏情况和可承受代价。"],
  },
  {
    id: "the-magician",
    name: "魔术师",
    arcana: "major",
    number: 1,
    keywords: ["意志", "资源", "表达", "创造"],
    upright: "你已经拥有可用的工具，关键是把想法、语言和行动对齐。不要再等外界许可。",
    reversed: "能量分散或表达失真。你可能有能力，却还没有把资源组织成一个清晰动作。",
    archetype: "创造者",
    light: "把资源转化为行动。",
    shadow: "操控、炫技、承诺超过执行。",
    reflectionQuestions: ["我手上已经有哪些资源？", "我最需要对齐的行动是什么？"],
    actionAdvice: ["列出三个可用资源。", "今天只推进一个最关键动作。"],
  },
  {
    id: "the-high-priestess",
    name: "女祭司",
    arcana: "major",
    number: 2,
    keywords: ["直觉", "沉默", "秘密", "内在"],
    upright: "答案尚未完全浮出水面。请给直觉一点空间，观察重复出现的感受和线索。",
    reversed: "你可能忽略了内在信号，或把沉默变成回避。需要分辨直觉和投射。",
    archetype: "内在知者",
    light: "安静、敏锐、能听见深层信息。",
    shadow: "封闭、暧昧、逃避表达。",
    reflectionQuestions: ["我一直知道却不愿承认的是什么？", "哪些事实还没有被说出来？"],
    actionAdvice: ["先记录感受，不急着解释。", "把事实和猜测分成两栏。"],
  },
  {
    id: "the-empress",
    name: "女皇",
    arcana: "major",
    number: 3,
    keywords: ["滋养", "丰盛", "身体", "创造"],
    upright: "这件事需要被滋养，而不是被催熟。关注身体、关系和真实需要，会让创造力自然回来。",
    reversed: "你可能在过度付出，或对自己太苛刻。丰盛不是消耗自己换来的。",
    archetype: "滋养者",
    light: "丰盛、接纳、创造生命力。",
    shadow: "过度照顾、依赖、忽略边界。",
    reflectionQuestions: ["我需要怎样被照顾？", "我正在滋养什么，也正在消耗什么？"],
    actionAdvice: ["安排一次身体层面的恢复。", "停止一件只消耗不滋养的事。"],
  },
  {
    id: "the-emperor",
    name: "皇帝",
    arcana: "major",
    number: 4,
    keywords: ["结构", "边界", "责任", "秩序"],
    upright: "现在需要清晰规则和承担。把模糊期待变成安排、边界和可执行计划。",
    reversed: "控制感可能过强或过弱。你需要的是稳定结构，不是压迫自己或别人。",
    archetype: "建立秩序者",
    light: "稳定、负责、能建立边界。",
    shadow: "僵硬、控制、害怕失控。",
    reflectionQuestions: ["哪里需要更明确的边界？", "我愿意承担哪部分责任？"],
    actionAdvice: ["设定一个明确期限。", "把一条边界说清楚。"],
  },
  {
    id: "the-hierophant",
    name: "教皇",
    arcana: "major",
    number: 5,
    keywords: ["信念", "传统", "学习", "指导"],
    upright: "你需要回到一套可靠的方法，或向有经验的人学习。不是所有问题都要独自摸索。",
    reversed: "旧规则可能不再适合你。请分辨哪些信念是你的，哪些只是被继承来的。",
    archetype: "导师",
    light: "传承、学习、稳定价值。",
    shadow: "教条、从众、把权威外包。",
    reflectionQuestions: ["我正在遵守谁的规则？", "我需要向谁请教？"],
    actionAdvice: ["找一个可靠参考。", "写下你真正认可的原则。"],
  },
  {
    id: "the-lovers",
    name: "恋人",
    arcana: "major",
    number: 6,
    keywords: ["选择", "关系", "价值", "连接"],
    upright: "关系或选择正在考验你的价值排序。真正的连接需要诚实，而不是只追求和谐。",
    reversed: "你可能在讨好、分裂或逃避选择。请回到自己的真实价值。",
    archetype: "选择与联结",
    light: "亲密、诚实、价值一致。",
    shadow: "依赖、犹豫、价值冲突。",
    reflectionQuestions: ["这个选择体现了我的哪种价值？", "我在关系里隐藏了什么真实感受？"],
    actionAdvice: ["说出一个真实偏好。", "把选择标准写下来。"],
  },
  {
    id: "the-chariot",
    name: "战车",
    arcana: "major",
    number: 7,
    keywords: ["意志", "推进", "掌控", "胜利"],
    upright: "方向比速度更重要。把分裂的力量收拢，你就能稳稳推进。",
    reversed: "你可能在硬撑，或让外界拉着你走。先找回方向盘。",
    archetype: "驾驭者",
    light: "集中、推进、自我掌控。",
    shadow: "蛮力、失控、目标混乱。",
    reflectionQuestions: ["我真正要去哪里？", "有哪些力量在拉扯我？"],
    actionAdvice: ["明确一个本周目标。", "砍掉一个分散注意力的选项。"],
  },
  {
    id: "strength",
    name: "力量",
    arcana: "major",
    number: 8,
    keywords: ["温柔", "勇气", "耐心", "驯服"],
    upright: "真正的力量不是压制，而是温柔地面对恐惧、欲望和脆弱。",
    reversed: "你可能对自己太狠，或把脆弱视为失败。需要恢复内在安全感。",
    archetype: "温柔的勇者",
    light: "耐心、勇气、稳定的自我接纳。",
    shadow: "自我否定、压抑、逞强。",
    reflectionQuestions: ["我正在压抑哪种感受？", "如果温柔一点，我会怎么做？"],
    actionAdvice: ["用一句话安抚自己。", "选择一个不靠硬撑的做法。"],
  },
  {
    id: "the-hermit",
    name: "隐者",
    arcana: "major",
    number: 9,
    keywords: ["独处", "内省", "寻找", "智慧"],
    upright: "你需要暂时离开噪音，听清自己的声音。答案更像一盏灯，不是聚光灯。",
    reversed: "独处可能变成孤立，或你一直在回避外界反馈。",
    archetype: "寻找者",
    light: "沉静、洞察、独立判断。",
    shadow: "封闭、疏离、过度自省。",
    reflectionQuestions: ["我需要从哪些声音里退出来？", "我已经独自想太久了吗？"],
    actionAdvice: ["安排一次不被打扰的复盘。", "只向一个可信的人求证。"],
  },
  {
    id: "wheel-of-fortune",
    name: "命运之轮",
    arcana: "major",
    number: 10,
    keywords: ["周期", "转机", "变化", "流动"],
    upright: "局势正在转动。你无法控制所有变量，但可以调整姿态，顺势抓住窗口。",
    reversed: "你可能卡在旧循环里。先看见重复模式，才有机会改变它。",
    archetype: "循环与转机",
    light: "顺势、适应、看见周期。",
    shadow: "宿命感、重复模式、失去主动。",
    reflectionQuestions: ["这个模式出现过几次？", "我能掌控的变量是什么？"],
    actionAdvice: ["写下可控和不可控两栏。", "在窗口期做一个小决定。"],
  },
  {
    id: "justice",
    name: "正义",
    arcana: "major",
    number: 11,
    keywords: ["公平", "事实", "因果", "决定"],
    upright: "请回到事实、责任和后果。清晰判断会比情绪反应更有力量。",
    reversed: "你可能在回避责任，或用片面信息做判断。需要重新校准公平。",
    archetype: "审视者",
    light: "诚实、平衡、负责任。",
    shadow: "偏见、逃避、过度审判。",
    reflectionQuestions: ["事实是什么，解释是什么？", "这个决定的代价由谁承担？"],
    actionAdvice: ["列出已知事实。", "推迟一个情绪化决定。"],
  },
  {
    id: "the-hanged-man",
    name: "倒吊人",
    arcana: "major",
    number: 12,
    keywords: ["暂停", "换位", "臣服", "等待"],
    upright: "暂停不是失败，而是换一个角度看问题。现在适合松开执念。",
    reversed: "你可能在无意义地拖延，或把牺牲当成价值感来源。",
    archetype: "换位者",
    light: "接纳、观察、重新理解。",
    shadow: "停滞、委屈、被动等待。",
    reflectionQuestions: ["如果换个角度，问题会变成什么？", "我抓得太紧的是什么？"],
    actionAdvice: ["暂停 24 小时再回应。", "写下另一个人的视角。"],
  },
  {
    id: "death",
    name: "死神",
    arcana: "major",
    number: 13,
    keywords: ["结束", "蜕变", "放手", "更新"],
    upright: "一个旧阶段正在结束。放手不是否定过去，而是为新生命腾出空间。",
    reversed: "你知道该结束，却还在拖住旧壳。抗拒让转化更痛。",
    archetype: "转化者",
    light: "清理、更新、诚实告别。",
    shadow: "抗拒变化、沉迷旧模式。",
    reflectionQuestions: ["什么已经结束了？", "我还在抓住哪个旧身份？"],
    actionAdvice: ["完成一个告别动作。", "清理一个旧承诺或旧物件。"],
  },
  {
    id: "temperance",
    name: "节制",
    arcana: "major",
    number: 14,
    keywords: ["调和", "耐心", "整合", "疗愈"],
    upright: "不要急着极端化。不同部分可以被调和，慢慢找到合适比例。",
    reversed: "节奏失衡，可能太急、太满或太分裂。先恢复中间地带。",
    archetype: "调和者",
    light: "耐心、整合、温和疗愈。",
    shadow: "失衡、过度、无法协调。",
    reflectionQuestions: ["哪些部分需要被调和？", "我最近哪里过量了？"],
    actionAdvice: ["减少一个过度刺激源。", "选择一个温和但持续的动作。"],
  },
  {
    id: "the-devil",
    name: "恶魔",
    arcana: "major",
    number: 15,
    keywords: ["束缚", "欲望", "执念", "阴影"],
    upright: "看见束缚，才有机会松绑。请诚实面对欲望、依赖和交换条件。",
    reversed: "你正在意识到旧束缚，也许已经可以开始解除它。",
    archetype: "阴影镜子",
    light: "诚实看见欲望和代价。",
    shadow: "沉迷、依赖、自我欺骗。",
    reflectionQuestions: ["我从这个束缚里得到了什么？", "我不愿承认的代价是什么？"],
    actionAdvice: ["说出一个真实诱因。", "设置一个具体限制。"],
  },
  {
    id: "the-tower",
    name: "高塔",
    arcana: "major",
    number: 16,
    keywords: ["瓦解", "真相", "冲击", "重建"],
    upright: "不稳固的结构正在崩塌。冲击痛苦，但也让真相无法再被忽略。",
    reversed: "你可能已经感到结构松动，却还在避免面对。越早修正，代价越小。",
    archetype: "拆除者",
    light: "打破幻象、释放真实。",
    shadow: "抗拒崩塌、灾难化想象。",
    reflectionQuestions: ["什么其实早就不稳了？", "真相出现后，我能重建什么？"],
    actionAdvice: ["先处理最现实的安全问题。", "不要急着粉饰太平。"],
  },
  {
    id: "the-star",
    name: "星星",
    arcana: "major",
    number: 17,
    keywords: ["希望", "疗愈", "愿景", "清澈"],
    upright: "经历混乱之后，希望正在恢复。请相信缓慢修复也是真实进展。",
    reversed: "你可能暂时看不见希望。先从恢复体力和信任开始，不必强迫乐观。",
    archetype: "疗愈者",
    light: "清澈、信任、重新连接愿景。",
    shadow: "失望、断联、过度理想化。",
    reflectionQuestions: ["什么让我重新有一点希望？", "我需要怎样的修复？"],
    actionAdvice: ["做一件恢复信任的小事。", "把愿景写成一句朴素的话。"],
  },
  {
    id: "the-moon",
    name: "月亮",
    arcana: "major",
    number: 18,
    keywords: ["迷雾", "梦境", "恐惧", "潜意识"],
    upright: "现在信息不完整，情绪和想象会放大不安。先不要把猜测当事实。",
    reversed: "迷雾正在散开。你可以开始辨认哪些恐惧来自过去，哪些属于当下。",
    archetype: "梦境之门",
    light: "敏感、想象、接触潜意识。",
    shadow: "混乱、投射、自我怀疑。",
    reflectionQuestions: ["我知道的事实是什么？", "我害怕的画面来自哪里？"],
    actionAdvice: ["先收集事实再判断。", "记录梦、情绪和触发点。"],
  },
  {
    id: "the-sun",
    name: "太阳",
    arcana: "major",
    number: 19,
    keywords: ["清晰", "喜悦", "生命力", "显现"],
    upright: "事情变得明亮。把真实的自己带到阳光下，成果会更自然地显现。",
    reversed: "快乐被遮住了，不代表它不存在。你可能需要减少自我否定。",
    archetype: "光明之子",
    light: "清楚、坦率、充满生命力。",
    shadow: "自我压抑、幼稚乐观或不敢被看见。",
    reflectionQuestions: ["什么让我感到真正明亮？", "我害怕被谁看见？"],
    actionAdvice: ["公开一个小成果。", "安排一件纯粹让你开心的事。"],
  },
  {
    id: "judgement",
    name: "审判",
    arcana: "major",
    number: 20,
    keywords: ["觉醒", "召唤", "复盘", "重生"],
    upright: "你正在听见更深的召唤。复盘过去不是为了责备，而是为了回应新的自己。",
    reversed: "你可能还被旧评价困住。需要把别人的声音和自己的召唤分开。",
    archetype: "觉醒者",
    light: "复盘、更新、回应使命感。",
    shadow: "自责、逃避召唤、害怕改变身份。",
    reflectionQuestions: ["这段经历想唤醒我什么？", "我不想再被哪个评价定义？"],
    actionAdvice: ["写一段阶段复盘。", "做一个代表重启的小行动。"],
  },
  {
    id: "the-world",
    name: "世界",
    arcana: "major",
    number: 21,
    keywords: ["完成", "整合", "圆满", "新阶段"],
    upright: "一个循环正在完成。你可以承认自己的成长，并把经验带入下一阶段。",
    reversed: "还有一个收尾动作没有完成。别急着开始新篇章，先把旧章节合上。",
    archetype: "完成者",
    light: "整合、成熟、阶段性圆满。",
    shadow: "拖延收尾、害怕结束、无法庆祝成果。",
    reflectionQuestions: ["我完成了什么？", "还差哪个收尾动作？"],
    actionAdvice: ["写下这阶段的三个收获。", "完成一个明确的收尾。"],
  },
];

export const MINOR_ARCANA: TarotCard[] = createMinorArcana();

export const TAROT_DECK: TarotCard[] = [...MAJOR_ARCANA, ...MINOR_ARCANA];
